### ISSUE TITLE
Still Asks to install Skype for Web Plugin

### ISSUE THREAD

**Issue by rushsteve1** [stanfieldr/ghetto-skype#10] opened 2016-05-16 21:59 UTC
After installing the RPM on openSUSE Tumbleweed when I go to make or receive a call it still asks to install the Skype for Web plugin.

This is obviously a real problem as it defeats the point of using Ghetto Skype at all.

**Comment by stanfieldr** [comment] 2016-05-17 00:52
I will try to reverse engineer how it works. If anyone wants to help, please feel free to pitch ideas.

**Comment by miyoyo** [comment] 2016-05-17 18:36
Mac and Windows seems to have the same behaviour when interacting with WebSkype

**Comment by rushsteve1** [comment] 2016-05-17 20:19
The person I am trying to call is on the Windows desktop client. When I attempt to call them it does not ask for the plugin, but they do not receive the call at all. When they try to call me it prompts for the plugin. They have the newest version of Skype, and I have 1.2.1 version from the releases page.

**Comment by stanfieldr** [comment] 2016-05-18 07:20
So I did a little more digging and I don't think duck tape is going to fix this one. Unfortunately we're going to have to wait for Skype to progress in their ORTC/WebRTC development/availability.

In the mean time, I'm going to see if I can make a fake Skype plugin for Linux. However, I can't make any promises so for now I'm updating the readme and closing this until we have a possible solution.

**Comment by rushsteve1** [comment] 2016-05-18 23:40
Well crap. Micro$oft at it again. Hope the fake plugin goes well because I really liked this project.

**Comment by fermulator** [comment] 2016-06-02 11:49
Same issues here.
Contact me if you need help with development and/or testing.

**Comment by fermulator** [comment] 2016-06-02 12:44
(how can we re-open this issue -- it's not fixed)

**Comment by stanfieldr** [comment] 2016-06-02 21:08
Yea if you want to take a stab at this issue and open a pull request so we can collaborate, that would be great. It's a bit difficult for me to work on this with my full time programming job.

I figure since the chrome Skype plugin source code can be read in it's original form, that would be a good starting point to get the gist of how our plugin should interact with Web Skype which should make interpreting disassembled code a little easier. If the DLLs are useful from the MSI file, we could write the plugin in C# and utilize them, but it's likely they won't be useful. We'll have to explore a little bit, but that's my current thoughts moving forward. In theory we can support video too at that point which would be awesome.

**Comment by mcarans** [comment] 2016-06-16 12:37
Does it need full plugin functionality or just a "does plugin exist" call to be faked?

**Comment by M1cha** [comment] 2016-07-09 06:19
u can make Skype4Web fully functional(like in the MS Edge browser) by setting the user agent to that browser. this way al features get enabled(video/audio calls, no plugin required, all kinds of file transfers).

this is how I do it in Chrome using Tampermonkey:
`
    // Your code here...
    navigator.__defineGetter__('userAgent', function(){
        return 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586';
    });`

**Comment by patrakov** [comment] 2016-07-09 18:11
Not really. This user agent will still ask you to install plugin if a linux user calls you.

**Comment by mcarans** [comment] 2016-07-09 18:16
@M1cha I've emailed you to ask this but perhaps even better if you answer here: 
Please can you confirm do Skype audio calls and group calls work for you with user agent set to Edge in Chrome for Linux? If so, what version of Chrome are you using and what flavour and version of Linux?

Thanks,
Mike

**Comment by M1cha** [comment] 2016-07-09 18:31
@patrakov It's important to make the script load at 'document-start', because skype's scripts load pretty early.

**Comment by stanfieldr** [comment] 2016-07-09 18:40
@M1cha Yea we managed to get outbound calls working by setting user agent. I tried running your code on document-start in Chrome+Tampermonkey, but getting the same problem there when calling from my macbook.

@mcarans I think we need the plugin. I'm not entirely sure what it's doing at this point, looks like it acts as a bridge between the skype web page and skype servers. I have a buddy at my work that just built a Chrome extension, maybe I can ask him Monday. I'll also look up some tutorials to see if I can figure this out.

I'm not sure if electron supports chrome extensions, but if it does, I'll try to refactor theirs to work on Linux so we people who don't use Ghetto Skype can use it too. If electron doesn't support chrome extensions, it doesn't matter though, we can just use electron itself to facilitate the interaction between the site and the extension server.
[skype-calling.zip](https://github.com/stanfieldr/ghetto-skype/files/355689/skype-calling.zip)

**Comment by mcarans** [comment] 2016-07-09 19:04
I can confirm that a Skype test call works with the user agent change, but when receiving a call, then I am requested to install a plugin from a .msi file. Makes me wonder what exactly the plugin is doing if it is possible to make a call with no problem. As I understand it, Edge works without plugins, so somehow on an incoming call, Skype is detecting that the browser is not Edge or that the OS is not Windows.

It doesn't help under Linux of course, but to know a bit more about what is being detected by Skype, has anyone tried the Edge user agent in Chrome for Windows with no plugin installed? If it works for receiving calls then it would imply that it is the OS that is being detected rather than the browser.

**Comment by M1cha** [comment] 2016-07-09 19:15
@mcarans when I checked Skypes javascript code very quick(it's decompiled and HUGE), what I understood was that skype is 100% html5 compatible but if the browser is not IE Edge then it switches to the legacy plugin mode.

**Comment by mcarans** [comment] 2016-07-09 19:19
@M1cha Could the check for Edge in the Skype Javascript be overridden with a Tampermonkey script?

**Comment by M1cha** [comment] 2016-07-09 19:22
@mcarans that's what the useragent override does(skype calls navigator.userAgent which the script changes), but apparently sth. slips through when sbd. calls you.

Does it make any difference if the agent is changed for real?(doesn't Electron allow this?)

**Comment by M1cha** [comment] 2016-07-09 19:34
@mcarans I found sth. else that's used: navigator.appName. what does Edge return for that? I don't have access to a windows machine.

**Comment by julthon** [comment] 2016-07-09 20:08
It returns "Netscape"

2016-07-09 21:34 GMT+02:00 Michael Zimmermann <notifications@github.com>:

**Comment by M1cha** [comment] 2016-07-09 20:40
I just tried calls in both directions and it works perfectly. I dunno if it affected that but I've added this code to my tampermonkey script:
```
navigator.__defineGetter__('platform', function(){
    return 'Win32';
});
```

**Comment by stanfieldr** [comment] 2016-07-10 04:10
I just signed my life away to the Windows 10 EULA. Surprisingly, the Edge browser has the same problem where it tries to download the MSI file if receiving a call.

I managed to comprehend how the Chrome plugin works, it's actually really simple. And the way they do it makes it super simple to substitute Electron. It's basically using a pub sub model, we just have to provide coordination logic between the plugin and the web page. The plugin use standard input/output to communicate with the extension (or in our case Electron).

I think I'm going to start developing that piece first and then make a jerry rigged bridge to my MacBook to use it's plugin for the Video/Audio input/output and see if I have any success. If someone can figure out a way to install windows/mac plugin in the meantime through wine or something, that would be an awesome temporary solution until the other half of the plugin can be written.

**Comment by mcarans** [comment] 2016-07-10 15:35
@M1cha I tried your addition of 'platform' to the Tampermonkey script, but it did not work for me. I called from an Android phone to web Skype on Linux Chrome and it asked me to install the plugin.

**Comment by mcarans** [comment] 2016-07-10 15:58
@stanfieldr It is more than surprising, it's appalling because this post on [Skype's blog](http://blogs.skype.com/2016/04/15/new-seamless-skype-video-calling-on-microsoft-edge-preview/) claims Edge is plugin free. It then contradicts this in the the post by giving an extremely limited range of circumstances in which it is plugin free.
"All Skype one-to-one and group voice and video calls to and from Microsoft Edge browsers are plugin free.
All Skype one-to-one calls from Microsoft Edge to the latest versions of Skype for Windows and Skype for Mac are plug in free"

So you can't call Skype for Android for example.

**Comment by M1cha** [comment] 2016-07-10 19:17
let's stay tuned: https://community.skype.com/t5/Linux/Exciting-news-for-Linux-users/td-p/4430988

**Comment by M1cha** [comment] 2016-07-13 18:17
LOL about my lost post, they published the news now(quoting from omgubuntu)
'the client is built using the tried-and-trusted Chromium-based Electron shell and Node.js combo.'
missing features:
- No video calls
- No desktop screen sharing
- No support for running two clients at once
- No 32-bit Linux support

basically it sounds like they just compiled ghetto-skype...

**Comment by miyoyo** [comment] 2016-07-13 18:28
@M1cha The worst is that video calls could work on ghetto-skype

**Comment by stanfieldr** [comment] 2016-07-13 18:28
Missing some features from Ghetto Skype too :P I'm going to keep working on it till they prove they're going to maintain it. But hey they haven't updated it since they bought Skype, so it's progress

**Comment by WebFreak001** [comment] 2016-07-14 16:49
Inbound call from Android 6.0.1 skype to ghetto skype worked for me on ArchLinux

**Comment by miyoyo** [comment] 2016-07-14 23:11
I think since microsoft added webrtc support to skype the calling problem is fixed.

Still these c***s only copied ghetto-skype/Skype-unofficial-client

**Closed** 2019-09-17 17:21 UTC
Labels: help wanted, in-progress
