### ISSUE TITLE
Uninstalling stops at 75%

### ISSUE THREAD

**Issue by meliezer** [stanfieldr/ghetto-skype#65] opened 2016-07-21 08:53 UTC
Hello,
v1.4.0. Uninstalling stops at 75%.
Anyway, the application is removed.

Thanks,
Menashè

**Comment by stanfieldr** [comment] 2016-08-06 02:26
What distro and package manager did you use to remove it?

**Comment by meliezer** [comment] 2016-08-06 20:13
I've tried uninstalling it only on Linux Mint 18.

**Comment by stanfieldr** [comment] 2016-08-07 01:50
Weird. I went ahead and installed Mint 18 in Gnome boxes and removed Ghetto Skype through Synaptic Package Manager but it seems to be uninstalling. Also had no luck reproducing using apt-get purge. I will go ahead and close this, but if anyone else has this issue feel free to reopen.

**Closed by stanfieldr** 2016-08-07 01:50 UTC
