### ISSUE TITLE
Start Skype on login option resets on application restart

### ISSUE THREAD

**Issue by sebastian-c** [stanfieldr/ghetto-skype#123] opened 2017-03-24 11:32 UTC
Toggling the 'Automatically start Skype when you login to your desktop environment' option seems to work, but on restarting the application, the option is reset. This effectively means that it never starts on startup. I'm using Ubuntu 16.04.2 LTS.

**Comment by code-hunger** [comment] 2017-04-29 15:17
I can't reproduce this problem. 
Try to track the existence of `~/.config/autostart/ghetto-skype.desktop` before and after you enable the setting and before and after you close/open ghetto-skype.
And what do you mean by "restarting the application" - refreshing the page (Ctrl+R) or kill the process?

**Comment by sebastian-c** [comment] 2017-05-02 08:48
Before I change the setting, the file is:
```
[Desktop Entry]
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Ghetto Skype
Name=Ghetto Skype
Comment[en_US]=Starts Ghetto skype
Comment=Starts Ghetto skype
Exec=/opt/Ghetto\ Skype/ghetto-skype
```

The permissions are `-rw-rw-r--`. Changing the setting prompts it to restart and no change is made to the file. Ghetto Skype restarts, but the window is completely blank. Reload/Refresh simply reloads the same blank window. Right clicking on the icon in the system tray and clicking 'Quit', then restarting it works and it loads normally, however, the toggle button has been reset to its initial unset position.

**Comment by code-hunger** [comment] 2017-05-02 12:33
This .desktop file is an instruction to the DE - in your case gnome, I suppose - to run the given executable (the one on the `Exec` line).

The file `~/.config/autostart/ghetto-skype.desktop`, when it exists, is a symlink to a system-wide desktop file `/usr/share/applications/ghetto-skype.desktop`.

If the symlink exists, then the setting should be "*on*" and you should not have to do anything - because your DE will find it and will start skype when you log in to your computer.

I do not get any prompt when changing the setting so we probably use different versions. Anyway, if you see the valid symling there, and log out and log in, then ghetto-skype should autostart.

**Comment by sebastian-c** [comment] 2017-05-02 13:30
I think that's my problem, there's no symlink. The file is present in `~/.config/autostart/` and the corresponding file present in `/usr/share/applications/` is empty. I can fix it manually, but is there a utility or something to fix the issue? Something to refresh config settings? I tried uninstalling and reinstalling, but that didn't work.

**Comment by stanfieldr** [comment] 2017-10-06 03:17
It looks like there was a bug in where the option would unselect itself the next time the page loaded even though the file existed in `~/.config/autostart/ghetto-skype.desktop`. If I understand correctly this has been fixed on the develop branch and will be included in the next release.

**Closed by stanfieldr** 2017-10-06 03:17 UTC
